# Generated by Django 3.1.5 on 2021-01-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(upload_to='project/')),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
